version: "3.8"

services:
  database:
    image: percona
    container_name: percona
    ports:
        - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: percona
    volumes:
        - ./var/lib/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: php
    ports:
      - 8080:80
    links:
      - database:db

  wordpress:
    image: wordpress
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 1234
      WORDPRESS_DB_NAME: percona
    volumes:
      - ./var/www/html:/var/www/html
    ports:
      - 20080:80
    links:
      - database:db

  elasticsearch:
    image: elasticsearch:7.14.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD:-1234}

  kibana:
    image: kibana:7.14.2
    container_name: kibana
    ports:
      - "5601:5601"

  filebeat:
    user: root
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.14.2
    volumes:
      - /var/run/docker.sock:/host_docker/docker.sock
      - /var/lib/docker:/host_docker/var/lib/docker
      - ./mysql_log:/mysql_log
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-node1}
      - KIBANA_HOST=${KIBANA_HOST:-node1}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-1234}
    command: ["--strict.perms=false"]
